site_name: ratatui-py
site_description: Python bindings for Ratatui (Rust TUI)
site_url: https://holo-q.github.io/ratatui-py/
repo_url: https://github.com/holo-q/ratatui-py
theme:
  name: material
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Demos: demos.md
  - API: api.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
