name: Render snapshots (grid only)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'scripts/generate_text_snapshots.py'
      - '.github/workflows/render-gif.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package and deps
        env:
          RATATUI_FFI_AUTO_BUILD: 1
          RATATUI_FFI_TAG: v0.2.0
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pillow
      - name: Generate image snapshots and grid
        run: |
          python3 scripts/generate_image_snapshots.py docs/snapshots.md README.md
      - name: Commit snapshots if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update image snapshots grid"
          file_pattern: |
            docs/snapshots.md
            README.md
            docs/assets/snapshots/*.png
