name: Render screencasts (GIF/MP4 + grid)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/assets/*.cast'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  cast_to_gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust + tools
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          "$HOME/.cargo/bin/cargo" install agg --locked

      - name: Render screencasts from index (GIF/MP4)
        run: |
          bash scripts/render_screencasts.sh -f

      - name: Generate snapshots grid
        run: |
          python3 scripts/generate_snapshot_grid.py scripts/screencasts.tsv docs/snapshots.md

      - name: Commit rendered assets and grid if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update screencast GIF/MP4 and snapshots grid"
          file_pattern: |
            docs/assets/*.gif
            docs/assets/*.mp4
            docs/snapshots.md
